name: Weekly Ingestion

on:
  schedule:
    - cron: '0 0 * * 0' # Sunday 00:00 UTC
  workflow_dispatch: # manual trigger for testing

jobs:
  run:
    name: Run worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl machine run . --dockerfile Dockerfile.worker --app wphd-prod --region syd --vm-memory 256 --restart no
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
